### ISSUE TITLE
Integration with AdonisJS

### ISSUE THREAD

**Issue by DaveLomber** [felixmosh/bull-board#212]
Hi everyone

Did someone try to connect the bull board into AdonisJS?

AdonisJS is based on top of express js, so seems there should be a way to do so

Here is a doc for Routing https://adonisjs.com/docs/4.1/routing

If someone can help - will be much appreciated

**Comment by felixmosh** [comment]
I've reviewed adonis.js api, it's router is not based on express, you can write small adapter (proxy) handler between adonis => express.

Each express router (the thing that we export) has `.handle(req, res)` which gets express req & res.

**Comment by rodrigorz** [comment]
Hi @felixmosh, i am using AdonisJS (v5) and is there an example of what the adapter between adonis => express should look like?

I need to show bull-board on an authenticated route, handled by Adonis router.
😄

**Comment by felixmosh** [comment]
> Hi @felixmosh, i am using AdonisJS (v5) and is there an example of what the adapter between adonis => express should look like?
> 
> I need to show bull-board on an authenticated route, handled by Adonis router.
> 😄

Unfortunately, I'm not familiar with `Adonis`, so I can't help with it.

If you be able to create such adapter, I will more then happy to add an example with `Adonis.js` 🙏🏼

**Comment by felixmosh** [comment]
Since v3.0.0 it is easy task to write adonis.js adapter.
Ping me if you need some help :)

**Comment by brkn** [comment]
I've spent couple of hours into writing an AdonisJs v5 adapter. It's not an easy task at all.

1. Unfortunately AdonisJs doesn't have a way of setting a rendering engine, so this means it's impossible to use `ejs` templates without porting them into adonis' edge templates.

2. Error handling is very different at adonisjs, you don't catch errors defensively. It doesn't fit like it does with other micro frameworks. Workaround is there, sending an error response manually.

3. `ServerAdapter` interface needs at least jsdoc explanations. Instead of using a constructor method you implement ton of public methods but the `adonisAdapter` end users would never need any of the methods. Proper information hiding would hint authors how to implement the adapter.

**Comment by felixmosh** [comment]
@brkn thank you for your input. I'm not familiar with adonisjs. If you want to collab on it, i'm available to chat in discord.

**Comment by brkn** [comment]
This is how I've integrated if anyone is interested. https://github.com/brkn/adonis-bull-demo-app/pull/1

Once you create an alternative to `index.ejs` template like `bull_board.edge`, rest is straight forward.
