### ISSUE TITLE
Queue jobs: active/failed count in list

### ISSUE THREAD

**Issue by antirek** [felixmosh/bull-board#283]
I have a lot of queues. For fast view failed jobs - scroll list and select problem queue.

![Screenshot](https://user-images.githubusercontent.com/324436/120268113-714fb500-c2cf-11eb-941b-791ccef0282b.png)

**Comment by felixmosh** [comment]
Hi @antirek 
This request was discussed multiple time, we decided to put a quick overview in a special dashboard page (#258)

I will close this issue since it is a duplicate request.

If this issue is super important for you, you are welcome to prepare a PR for a dashboard page, it can be something simple, and we will refactor it as needed. :]

**Comment by antirek** [comment]
Thanks, 
dashboard - cool idea!
