### ISSUE TITLE
AdonisJS Support

### ISSUE THREAD

**Issue by kevin1193** [felixmosh/bull-board#416]
Does the newest version have adonisjs support?

**Comment by felixmosh** [comment]
Hi @kevin1193 , I've reviewed several times Adonis, and I didn't found a "clear" path to add support.
But, I'm not familiar with Adonis and probably I've missed something out.

Let me know If you willing to collaborate on writing an adapter for Adonis

**Comment by kevin1193** [comment]
Hello @felixmosh . Yeah I'm very willing to collab in regards to Adonisjs adapter for this. I need to use this in one of my projects. I will now fork this the main repo and do a run through with it. Please help with tips where do you think should I start.

**Comment by felixmosh** [comment]
I'm available at Discord, felixmosh#0178 ping me if you need IM.

**Comment by kevin1193** [comment]
Alright cool will do.

**Comment by kevin1193** [comment]
I added you as friend. I cant send dm unless you accept. Looking forward to talk to you.

**Comment by felixmosh** [comment]
I'm there.

**Comment by felixmosh** [comment]
Basically, Adonis adapter can return any thing (for example, in FastifyAdapter, we are returning a Fastify Plugin, In ExpressAdapter we are returning a router), it should "talk" with Adonis, setup several things, like:
1. Serving stating files
2. Rendering ejs (in one of the threads [brkn](https://github.com/brkn) mentioned that Adonis doesn't supports ejs, we for example can make a "middleware" route in the Adapter that will generate the ejs, and pass it to Adonis)
3. Register bull-board api routes

The basic idea of the architecture is based on Builder design pattern, [`createBullBoard`](https://github.com/felixmosh/bull-board/blob/fbace4bdbf0ac56f5ff6f171e112270536fa11aa/packages/api/src/index.ts#L8) gets queue list & framework adapter, and calls the [adapter's interface](https://github.com/felixmosh/bull-board/blob/fbace4bdbf0ac56f5ff6f171e112270536fa11aa/packages/api/src/index.ts#L18-L24) in-order to "build" (setup) the host.

Again, I'm not expecting you to solve the whole thing, but, I'm clueless (& don't use) Adonis, so I don't know where to start.
But I do know requirements in order to build an XAdapter, I'm available here or in discord.

**Comment by joaosilva0345** [comment]
> Again, I'm not expecting you to solve the whole thing, but, I'm clueless (& don't use) Adonis, so I don't know where to start.
> But I do know requirements in order to build an XAdapter, I'm available here or in discord.

I wanted to inform you that AdonisJS has released version 6. There's a package that seems to have implemented Bull-Board, but it doesn't appear to be maintained anymore: https://github.com/acidiney/bull-queue

The most widely used queue system package for AdonisJS 6 is this one: https://github.com/romainlanz/adonis-bull-queue

Perhaps checking it out might help you!
