### ISSUE TITLE
Feature: Pin job

### ISSUE THREAD

**Issue by theoilie** [felixmosh/bull-board#424]
It's currently difficult with fast-moving queues to view a job's data for more than 10 or 20 seconds because new jobs come in and push the job I'm looking at out of view. I saw another request about slowing down the refresh rate, but the ability to pin a job for viewing purposes would also be very helpful. Is that a planned feature or possibility? Thanks!

**Comment by felixmosh** [comment]
Hi @theoilie,
I didn't planned it since I don't have such requirement (and If I do, I can inspect the data on the "completed" tab).

It is possible to implement such a functionality, pretty easily, show a merged list of `pinned` + on going jobs, and add the ability to add / remove a job to the `pinned` list.

A PR will be very welcomed 🙏🏼

**Comment by theoilie** [comment]
> Hi @theoilie, I didn't planned it since I don't have such requirement (and If I do, I can inspect the data on the "completed" tab).
> 
> It is possible to implement such a functionality, pretty easily, show a merged list of `pinned` + on going jobs, and add the ability to add / remove a job to the `pinned` list.
> 
> A PR will be very welcomed 🙏🏼

Just saw your comment now -- thanks for the speedy feedback as usual! I may take a look at adding that this weekend. The main use case is when the queue has a maximum number of jobs, then the job I'm trying to inspect in the "completed" tab gets pushed down out of view every time a new job completes.
