### ISSUE TITLE
Feature request: Collapse job data

### ISSUE THREAD

**Issue by sroettering** [felixmosh/bull-board#529]
I have queues with large payloads and the bull board pages load very slowly. I did not investigate why it is so slow. I suspect rendering the job data as json takes for ever. Thus it would be nice if large objects/arrays would be auto-collapsed when rendering (similar to collapsing code lines in IDEs). This would also make job data more readable because you don't have to scroll down thousands of lines to see the properties that come after these big chunks. So collapsible json would be a nice regardless if it fixes the performance or not.

**Comment by felixmosh** [comment]
It probably will solve the performance, but It should be only a UX consideration.

If your json data is huge, you should use data formatter in order to reduce the size of the JSON, the app won't be able to reduce it for you.

But this is totally a nice UX optimization, it should be settings configurable.

**Comment by bennet-esyoil** [comment]
I face the same issue.

I write a lot of data and some payloads are huge and they completely break the Dashboard. Even when they are not being processed anymore or they should be on the second page, I cannot get it to load without my Browser killing the tab.

Only solution to make it usable again currently is to just kill the redis-container, delete and recreate it, which works and is fine in this use-case, but probably not in others.

**Comment by bennet-esyoil** [comment]
That could be a option. I'll need to figure out first if the data needs to be shown there, normally I wouldn't want to check each entry in the queues, but for debugging it's perfect. 

Anyways, I'll talk back with my team and see if it's a viable option. Thanks for the suggestion.

**Comment by Twisterking** [comment]
We are running into the same issue here!
We have very big payloads and bull-board is basically unuseable to us, as the browser just crashed because the DOM can't render the big JSONs! 

My recommendation would be to just create a setting (in the top right menu), where you can collapse the JSONs by default. Like this, hopefully, the DOM should not crash and it is then the user's job to just open the JSON (job data) for a single job as needed.

**Comment by felixmosh** [comment]
@Twisterking will able to prepare a PR for this?

**Comment by Twisterking** [comment]
Maybe, not sure yet! I was not aware of the `queueAdapter.setFormatter()` option, so we might be using just that and be happy with it! 👍

**Comment by felixmosh** [comment]
I'll add an additional optimization which will use webworker if available for highlighting code

**Comment by felixmosh** [comment]
@sroettering can you test `v4.12.1` which includes web worker highlight & collapse functionality (enabled from settings).
Try your heavy queue pls :]

**Comment by sroettering** [comment]
At first glance it looks very nice! Would have expected to be able to collapse the data again, but I guess it's ok like this. Performance is also good in my first test.
Thanks for the quick implementation. I will open more feature requests soon :-)

**Comment by felixmosh** [comment]
Did you tested the board without the collapse state?
Is it much better?

**Comment by sroettering** [comment]
yes, it's much better now. Also the paging is really fast as well!
