### ISSUE TITLE
flow children with groups are not visible in bullboard

### ISSUE THREAD

**Issue by apizzini** [felixmosh/bull-board#770]
When using [flows](https://docs.bullmq.io/guide/flows) and [groups](https://docs.bullmq.io/bullmq-pro/groups) (which is a bullmq pro feature), flow children jobs are not visible.

For example adding a flow like this (without children.*.opts.group):
```
      await this.searchBulkFlowProducer.add({
        name: "renovate-interior",
        queueName: "search-bulk",
        children: [
          { name: "paint", queueName: "search-bulk" },
          { name: "paint", queueName: "search-bulk" },
          { name: "fix", queueName: "search-bulk" },
        ],
      });
```

results in:
![Screenshot 2024-06-09 alle 17 28 30](https://github.com/felixmosh/bull-board/assets/5413702/7443bfe1-8d38-4e4a-a9c8-fdd34677ac18)

But adding a flow with children.*.opts.group like this:
```
      await this.searchBulkFlowProducer.add({
        name: "renovate-interior",
        queueName: "search-bulk",
        children: [
          { name: "paint", queueName: "search-bulk" },
          { name: "paint", queueName: "search-bulk" },
          { name: "fix", queueName: "search-bulk" },
        ].map((item) => ({
          ...item,
          opts: {
            group: { id: "group1" },
          },
        })),
      });
```

results in this

![Screenshot 2024-06-09 alle 17 30 43](https://github.com/felixmosh/bull-board/assets/5413702/67d44107-d2f4-4816-a58d-9567343b0def)

Bullmq processes all jobs, flow children are simply not visible in bullboard.

Are pro features out of context in bullboard or is there interest to have that handled?

I'll be more than happy to open a PR to fix this if bullboard intend to support this feature :)

**Comment by judsd** [comment]
Here is the improved text with corrected grammar:

---

Hello,

I ran into the same issue earlier. In our case, we are not using FlowProducer but just groups along with priority.

```javascript
group: {
    id: campaignId,
    priority: priority
}
```

I can confirm the issue remains even if the priority is removed.

I didn't dig deeper, but I assume since the library is using the standard [bullmq](https://github.com/felixmosh/bull-board/blob/master/packages/api/src/queueAdapters/bullMQ.ts) library, those jobs are not returned by the library.

I think a PR would be great if you already have a fix; otherwise, I can take a look at it by the end of the week.

Cheers,  
Jud

**Comment by judsd** [comment]
I took a look with the official UI at taskforce.sh, and it seems they have the same limitation at this time.

**Comment by judsd** [comment]
Hello,

I ran into the same issue earlier. In our case, we are not using FlowProducer but just groups along with priority.

```javascript
group: {
    id: campaignId,
    priority: priority
}
```

I can confirm the issue remains even if the priority is removed.

I didn't dig deeper, but I assume since the library is using the standard [bullmq](https://github.com/felixmosh/bull-board/blob/master/packages/api/src/queueAdapters/bullMQ.ts) library, those jobs are not returned by the library.

I think a PR would be great if you already have a fix; otherwise, I can take a look at it by the end of the week.

On a side note, I checked the official UI at taskforce.sh, and it appears they have the same limitation at this time.

Cheers,  
Jud

**Comment by Matanya7491** [comment]
So, how i can support groups in bull-borad?
just with priority?

**Comment by felixmosh** [comment]
How can I get the bullmq-pro?
what is this groups feature?

**Comment by Matanya7491** [comment]
It's an important feature to understand how to view the division in Bull-Board according to the groups in Bull-Pro.
https://docs.bullmq.io/bullmq-pro/groups.

Taskforce using a free token or are interested in using Taskforce on a trial basis.
https://taskforce.sh/

Need to log in and get a token for npm registry
https://docs.taskforce.sh/bullmq-pro

We can see the division according to the groups in Redis Insight.
![image](https://github.com/user-attachments/assets/f898ea3f-f7cd-487e-82f4-fdc517bab985)

 This is helpful for us, and we would like to know how to support this feature in Bull-Board as well?
 
 Thanks for the answer and for the great library!

**Comment by felixmosh** [comment]
Yeah, it seems that "groups" were implemented by adding the group name into the name of the queue.
I'm not sure how (if at all) bull-board supports bullmq-pro lib, I've not tested it at all.

If you have time, I'll more than happy to review a PR for this.

**Comment by Matanya7491** [comment]
I'll try to see how I can support it and will update you.
Thank you very much.
